# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bilateral_lattice3d_cpp <- function(vol3d, mask3, sigma_sp, sigma_r, guide_, guides_, blur_iters) {
    .Call(`_fmrismooth_bilateral_lattice3d_cpp`, vol3d, mask3, sigma_sp, sigma_r, guide_, guides_, blur_iters)
}

bilateral_lattice4d_cpp <- function(vec4d, mask3, sigma_sp, sigma_t, sigma_r, guide_spatial_, guides_, design_, sigma_d, blur_iters) {
    .Call(`_fmrismooth_bilateral_lattice4d_cpp`, vec4d, mask3, sigma_sp, sigma_t, sigma_r, guide_spatial_, guides_, design_, sigma_d, blur_iters)
}

mppca4d_core <- function(vec4d, mask3, patch, tw, stride, sigma) {
    .Call(`_fmrismooth_mppca4d_core`, vec4d, mask3, patch, tw, stride, sigma)
}

permutohedral_lattice3d_cpp <- function(vol3d_, mask3_, sigma_sp_, sigma_r_, guide_, guides_, passes_) {
    .Call(`_fmrismooth_permutohedral_lattice3d_cpp`, vol3d_, mask3_, sigma_sp_, sigma_r_, guide_, guides_, passes_)
}

permutohedral_lattice4d_cpp <- function(vec4d_, mask3_, sigma_sp_, sigma_t_, sigma_r_, guide_spatial_, guides_, design_, sigma_d_, passes_) {
    .Call(`_fmrismooth_permutohedral_lattice4d_cpp`, vec4d_, mask3_, sigma_sp_, sigma_t_, sigma_r_, guide_spatial_, guides_, design_, sigma_d_, passes_)
}

tv_robust_4d_cpp <- function(vec4d, mask3, lambda_s, lambda_t, delta, outer_loops, iters, wt_in) {
    .Call(`_fmrismooth_robust_tv_huber_4d_cpp`, vec4d, mask3, lambda_s, lambda_t, delta, outer_loops, iters, wt_in)
}

tv_tukey_4d_cpp <- function(vec4d, mask3, lambda_s, lambda_t, cthresh, alpha, wt_edge, iters, tau, sigma, theta) {
    .Call(`_fmrismooth_tv_tukey_4d_cpp`, vec4d, mask3, lambda_s, lambda_t, cthresh, alpha, wt_edge, iters, tau, sigma, theta)
}

guided3d_core <- function(vol, guide, mask, radius, eps) {
    .Call(`_fmrismooth_guided3d_core`, vol, guide, mask, radius, eps)
}

temporal_guided1d_core <- function(vec4d, gtemp, w, mask3, radius_t, eps_t) {
    .Call(`_fmrismooth_temporal_guided1d_core`, vec4d, gtemp, w, mask3, radius_t, eps_t)
}

tv_denoise_4d_cpp <- function(vec4d, mask3, lambda_s, lambda_t, iters, tau, sigma, theta) {
    .Call(`_fmrismooth_tv_denoise_4d_cpp`, vec4d, mask3, lambda_s, lambda_t, iters, tau, sigma, theta)
}

